### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

### ISSUE THREAD

**Issue by Santhosh1509** [ayooshkathuria/pytorch-yolo-v3#103]
OS: Windows 10
Python version: 3.7.2
Pip list of libraries installed inside virtual environment

> Package               Version
> --------------------- --------
> cycler                0.10.0
> Cython                0.29.11
> kiwisolver            1.1.0
> matplotlib            3.1.1
> numpy                 1.16.4
> object-detection      0.1
> opencv-contrib-python 4.1.0.25
> opencv-python         4.1.0.25
> Pillow                6.1.0
> pip                   19.1.1
> pyparsing             2.4.0
> python-dateutil       2.8.0
> setuptools            41.0.1
> six                   1.12.0
> torch                 1.1.0
> torchvision           0.3.0
> wheel                 0.33.4

getting this error

> Traceback (most recent call last):
>   File "video_demo.py", line 169, in <module>
>     output = write_results(output, confidence, num_classes, nms = True, nms_conf = nms_thesh)
>   File "D:\vehicle-detection\util.py", line 177, in write_results
>     ious = bbox_iou(image_pred_class[i].unsqueeze(0), image_pred_class[i+1:])
>   File "D:\vehicle-detection\bbox.py", line 74, in bbox_iou
>     inter_area = torch.max(inter_rect_x2 - inter_rect_x1 + 1,torch.zeros(inter_rect_x2.shape))*torch.max(inter_rect_y2 - inter_rect_y1 + 1, torch.zeros(inter_rect_x2.shape))
> RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'
> 

```
img, orig_im, dim = prep_image(frame, inp_dim)
            
im_dim = torch.FloatTensor(dim).repeat(1,2)                        
            
            
if CUDA:
     im_dim = im_dim.cuda()
     img = img.cuda()
            
     with torch.no_grad():   
          output = model(Variable(img), CUDA)            
            
          output = write_results(output, confidence, num_classes, nms = True, nms_conf = nms_thesh)
```
Even running this code on GPU giving the same error
https://github.com/ayooshkathuria/pytorch-yolo-v3/blob/master/video_demo.py
what's going wrong?

**Comment by Santhosh1509** [comment]
My bad
Had an extra line of code 
https://github.com/ayooshkathuria/pytorch-yolo-v3/blob/master/bbox.py

line 72
`inter_area = torch.max(inter_rect_x2 - inter_rect_x1 + 1,torch.zeros(inter_rect_x2.shape))*torch.max(inter_rect_y2 - inter_rect_y1 + 1, torch.zeros(inter_rect_x2.shape))`

remove it started working fine
