### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by chuckwoody** [ayooshkathuria/pytorch-yolo-v3#108]
Loading network.....
Network successfully loaded
Traceback (most recent call last):
  File "D:/pytorch-yolo-v3-master/detect.py", line 150, in <module>
    batches = list(map(prep_image, imlist, [inp_dim for x in range(len(imlist))]))
  File "D:\pytorch-yolo-v3-master\preprocess.py", line 39, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by ZongkaiLiu** [comment]
I got the same error. How to fix it?

**Comment by everRoc** [comment]
same error,help!!

**Comment by everRoc** [comment]
OK, I got the answer...The dictionary of images can not contain Chinese characters, damn it！
