### ISSUE TITLE
video object detection for half precision (FP16) throwing error

### ISSUE THREAD

**Issue by spaul13** [ayooshkathuria/pytorch-yolo-v3#123]
while running the object detection using video_demo_half.py script (16-bit half precision floats), I am getting the following error

_Traceback (most recent call last):
  File "video_demo_half.py", line 112, in <module>
    **model(get_test_input(inp_dim, CUDA), CUDA)**
  File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\yolo\yolov3_PyTorch\darknet.py", line 319, in forward
    x = self.module_list[i](x)
  File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
**RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same**_

**Comment by Henylab** [comment]
> while running the object detection using video_demo_half.py script (16-bit half precision floats), I am getting the following error
> 
> _Traceback (most recent call last): File "video_demo_half.py", line 112, in **model(get_test_input(inp_dim, CUDA), CUDA)** File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\module.py", line 477, in **call** result = self.forward(*input, **kwargs) File "C:\yolo\yolov3_PyTorch\darknet.py", line 319, in forward x = self.module_list[i](x) File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\module.py", line 477, in **call** result = self.forward(*input, **kwargs) File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\container.py", line 91, in forward input = module(input) File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\module.py", line 477, in **call** result = self.forward(*input, **kwargs) File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward self.padding, self.dilation, self.groups) **RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

Hi, Do you have solve this problem?
