### ISSUE TITLE
error in Different batch size in detect.py

### ISSUE THREAD

**Issue by Derekabc** [ayooshkathuria/pytorch-yolo-v3#18]
It seems the code can not work when I make a change to the batch size of detect.py
```
Traceback (most recent call last):
  File "/home/dong/PycharmProjects/SIMD/pytorch-yolo-v3/detect.py", line 200, in <module>
    prediction = write_results(prediction, confidence, num_classes, nms = True, nms_conf = nms_thesh)
  File "/home/dong/PycharmProjects/SIMD/pytorch-yolo-v3/util.py", line 155, in write_results
    img_classes = unique(image_pred_[:,-1])
IndexError: too many indices for tensor of dimension 1
```

**Comment by ayooshkathuria** [comment]
I've just pushed a fix. Please pull and let me know whether that works for you or not.
