### ISSUE TITLE
Sorry, I am a rookie, I downloaded your program, this problem occurs after running. Ask you for some question.Thank you very match!

### ISSUE THREAD

**Issue by zuochenrui** [ayooshkathuria/pytorch-yolo-v3#21]
Traceback (most recent call last):
  File "D:/deep_learn/pytorch-yolo-v3-master/pytorch-yolo-v3-master/video_demo_half.py", line 100, in <module>
    model.load_weights(args.weightsfile)
  File "D:\deep_learn\pytorch-yolo-v3-master\pytorch-yolo-v3-master\darknet.py", line 367, in load_weights
    fp = open(weightfile, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'yolov3.weights'

**Comment by ayooshkathuria** [comment]
You need to download yolov3.weights file

**Comment by saisiddharthaversion3** [comment]
Where shall I need to store it?, In cfg?
