### ISSUE TITLE
python video_demo.py --video 1.avi  has no results

### ISSUE THREAD

**Issue by lonngxiang** [ayooshkathuria/pytorch-yolo-v3#80]
File "video_demo.py", line 111, in <module>
    model(get_test_input(inp_dim, CUDA), CUDA)
  File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Lavector\Desktop\imageai\pytorch-yolo-v3-master\darknet.py", line 346, in forward
    x = outputs[i-1] + outputs[i+from_]
RuntimeError: CUDA out of memory. Tried to allocate 1.38 MiB (GPU 0; 1024.00 MiB total capacity; 520.90 MiB already allocated; 496.00 KiB free; 3.72 MiB cached)

Traceback (most recent call last):
  File "video_demo_half.py", line 112, in <module>
    model(get_test_input(inp_dim, CUDA), CUDA)
  File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Lavector\Desktop\imageai\pytorch-yolo-v3-master\darknet.py", line 319, in forward
    x = self.module_list[i](x)
  File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

**Comment by Paumila** [comment]
Hello,

I have the same error on both cases.

The first problem, I think you can solve using less --reso (resolution)

For the secon one, I have the same and I don't know how to solve it.

If someone can help to solve this issue?

Traceback (most recent call last):
File "video_demo_half.py", line 112, in 
model(get_test_input(inp_dim, CUDA), CUDA)
File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "C:\Users\Lavector\Desktop\imageai\pytorch-yolo-v3-master\darknet.py", line 319, in forward
x = self.module_listi
File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
input = module(input)
File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

**Comment by Henylab** [comment]
> File "video_demo.py", line 111, in
> model(get_test_input(inp_dim, CUDA), CUDA)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\Lavector\Desktop\imageai\pytorch-yolo-v3-master\darknet.py", line 346, in forward
> x = outputs[i-1] + outputs[i+from_]
> RuntimeError: CUDA out of memory. Tried to allocate 1.38 MiB (GPU 0; 1024.00 MiB total capacity; 520.90 MiB already allocated; 496.00 KiB free; 3.72 MiB cached)
> 
> Traceback (most recent call last):
> File "video_demo_half.py", line 112, in
> model(get_test_input(inp_dim, CUDA), CUDA)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\Lavector\Desktop\imageai\pytorch-yolo-v3-master\darknet.py", line 319, in forward
> x = self.module_list[i](x)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

Hi, Do you have solve this problem?

**Comment by Henylab** [comment]
> File "video_demo.py", line 111, in
> model(get_test_input(inp_dim, CUDA), CUDA)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\Lavector\Desktop\imageai\pytorch-yolo-v3-master\darknet.py", line 346, in forward
> x = outputs[i-1] + outputs[i+from_]
> RuntimeError: CUDA out of memory. Tried to allocate 1.38 MiB (GPU 0; 1024.00 MiB total capacity; 520.90 MiB already allocated; 496.00 KiB free; 3.72 MiB cached)
> 
> Traceback (most recent call last):
> File "video_demo_half.py", line 112, in
> model(get_test_input(inp_dim, CUDA), CUDA)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\Lavector\Desktop\imageai\pytorch-yolo-v3-master\darknet.py", line 319, in forward
> x = self.module_list[i](x)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\Lavector\python3\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

Hi, Do you have solve this problem?
