### ISSUE TITLE
shape '[1024, 512, 3, 3]' is invalid for input of size 2794830

### ISSUE THREAD

**Issue by BeLEEU** [ayooshkathuria/pytorch-yolo-v3#94]
Traceback (most recent call last):
  File "D:/DEEPL/pytorch-yolo-v3-master/detect.py", line 118, in <module>
    model.load_weights(args.weightsfile)
  File "D:\DEEPL\pytorch-yolo-v3-master\darknet.py", line 469, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 2794830

**Comment by fourth-archive** [comment]
@BeLEEU I recommend you try this YOLOv3 tutorial to solve your problem: 
https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data

The accompanying repository works on MacOS, Windows and Linux, includes multigpu and multithreading, performs inference on images, videos, webcams, and an iOS app. It also tests to slightly higher mAPs than darknet, including on the latest `YOLOv3-SPP.weights` (**60.7 COCO mAP**), and offers the ability to train custom datasets from scratch to darknet performance, all using PyTorch :)
https://github.com/ultralytics/yolov3

<table style="width:100%">
  <tr>
    <td>
      <img src="https://user-images.githubusercontent.com/26833433/56132958-9e279d80-5f8b-11e9-8d23-c34dbb2a39e6.jpg">
    </td>
    <td align="center">
    <a href="https://www.ultralytics.com" target="_blank">
    <img src="https://storage.googleapis.com/ultralytics/logo/logoname1000.png" width="200"></a>
    <a href="https://itunes.apple.com/app/id1452689527" target="_blank">
    <img src="https://user-images.githubusercontent.com/26833433/50044365-9b22ac00-0082-11e9-862f-e77aee7aa7b0.png" width="180"></a>
      <img src="https://user-images.githubusercontent.com/26833433/56132957-9d8f0700-5f8b-11e9-9067-0d91364c57c0.jpg">
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/26833433/56132991-b0094080-5f8b-11e9-89a1-62fb65b98d45.jpg">
    </td>
  </tr>
</table>

**Comment by Sam813** [comment]
@BeLEEU 
I have the same issue. have you solved it?

**Comment by OUYANGYAFEI** [comment]
did you solve it ,i met the same problem and i trapeed into it for a longtime ,i dont know it appears in the code
